# Generated by Django 4.2.15 on 2026-08-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_providerphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='address_full',
            field=models.TextField(blank=True, null=True, verbose_name='Полный адрес'),
        ),
        migrations.AddField(
            model_name='provider',
            name='experience_years',
            field=models.IntegerField(default=0, verbose_name='Опыт работы (лет)'),
        ),
        migrations.AddField(
            model_name='provider',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='provider',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='provider',
            name='price_from',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена от'),
        ),
        migrations.AddField(
            model_name='provider',
            name='price_to',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена до'),
        ),
    ]
