# Generated by Django 4.2.15 on 2026-08-03 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_provider_address_full_provider_experience_years_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='address_full',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='longitude',
        ),
    ]
